### ISSUE TITLE
Preview mode renders incorrectly

### ISSUE THREAD

**Issue by glaza** [siavashs/Prism#22]
Previewing the comment fails to render the code block. 

### Environment
JIRA v7.7.0
Server installation
RichText off

### Steps to reproduce:
* Create a code block
![CodeBlock](https://user-images.githubusercontent.com/33300759/58272345-48999a00-7d5c-11e9-89a7-5715ec960e4c.png)
* Click the bottom left "Preview" button, preview renders is a grey, disabled style that is unreadable.
![CodeBlockPreview](https://user-images.githubusercontent.com/33300759/58272347-48999a00-7d5c-11e9-9b0a-4a4325829697.png)
* Once the comment is added, the code block renders fine.
![CodeBlockAdded](https://user-images.githubusercontent.com/33300759/58272346-48999a00-7d5c-11e9-982a-884e6a3ddc55.png)

**Comment by siavashs** [comment]
We need to highlight the code after the user hits the preview button (this doesn't count as new content so it doesn't work currently).
But even calling the code highlighting function results in this:
![image](https://user-images.githubusercontent.com/113189/59977174-41211700-95ce-11e9-970d-14873ce6b7aa.png)
As you can see the background color is still missing.

**Comment by siavashs** [comment]
And the reason for background not being rendered is `div.wiki-edit pre` overriding it:
![image](https://user-images.githubusercontent.com/113189/59977508-38324480-95d2-11e9-8fc9-9f18325a0ab5.png)
If I disable `background: none` the background appears:
![image](https://user-images.githubusercontent.com/113189/59977515-5ac45d80-95d2-11e9-9256-fa9ec02a108f.png)
But what are the consequences of messing with JIRA's built-in CSS?

**Comment by idsvandermolen** [comment]
messing with JIRA's build-in CSS `div.wiki-edit pre` selector globally will soon break compatibility. But we can probably limit it to Prism code block within `div.wiki-edit pre <code block selector>` and hope Atlassian will keep this selector name stable.
(sorry, by CSS knowledge is pretty basic)

**Comment by siavashs** [comment]
I'm switching the plugin to a light theme and as a results the fonts render in black.
![image](https://user-images.githubusercontent.com/113189/75607849-640baf80-5afb-11ea-904f-77a365c81659.png)
So we will not need to add any custom CSS.
