### ISSUE TITLE
Prevent JS failure in case of typo (breaks agile board)

### ISSUE THREAD

**Issue by ymartin59** [siavashs/Prism#25]
When working in JIRA Software Agile Boards, such a mistake in a **comment**
```
{{code}
Stupid typo
{code}
```

triggers a JavaScript error "RangeError: invalid array length" in highlightAll[...] methods which breaks board features like comment edition and deletion, and prevents to fix mistake from board.

As a work-around, it is possible to open issue from /jira/browse/ISSUE-xxx where comment edition is still available to fix mistake and retrieve features in boards after a full page refresh.

Notice that same typo when editing Description field from board triggers JS error but edition to fix is still available.

**Comment by siavashs** [comment]
@ymartin59 can you please share the versions that you are using and if this issue still happens?

**Comment by ymartin59** [comment]
Just tested with Jira Software server 8.7.1 and Prism 1.2.4 and issue is now fixed.
