### ISSUE TITLE
Highlite rendering a line too high

### ISSUE THREAD

**Issue by flamein** [siavashs/Prism#27]
As reported by a user through Atlassian contact address
When using a code block like:

{code:c++|title=rmanshare/RIS/include/sharedComponents/PxrLightFilter.h|linenumbers|firstline=197|highlight=205-206}
        // transform all points
        RtInt res = lfCtx->Transform(RixShadingContext::k_AsPoints,
                                     US_NULL, _coordSys,
                                     numSamples, shadingCtxIndex,
                                     xformedP, xformedP,
                                     NULL, NULL);
        if (res != 0)
        {
            std::cerr << "Transform from 'current' to '" << _coordSys.CStr()
                      << "' did not work!" << std::endl;
        }
{code}

It will render a highlite like this:
<img width="584" alt="Screen Shot 2019-09-24 at 10 26 04 AM" src="https://user-images.githubusercontent.com/22610677/65587125-a0077b00-df85-11e9-91ab-f21b0895eec7.png">

**Comment by siavashs** [comment]
Opened a PR for upstream to fix this issue. https://github.com/PrismJS/prism/pull/2235

**Comment by siavashs** [comment]
New PR by upstream https://github.com/PrismJS/prism/pull/2237
