### ISSUE TITLE
Remove Catawiki branding

### ISSUE THREAD

**Issue by idsvandermolen** [siavashs/Prism#30]
After transfer of Prism plugin, we still need to remove Catawiki branding in the code and Atlassian Marketplace.
Let's use this issue to track this.

**Comment by siavashs** [comment]
@idsvandermolen should I keep Catawiki as copyright holder till 2020? or do you prefer to also remove that?

**Comment by idsvandermolen** [comment]
yeah, let's keep it till 2019 (inclusive), like it is in current LICENSE file.

**Comment by siavashs** [comment]
Please check https://github.com/siavashs/Prism/pull/33

**Comment by siavashs** [comment]
The Vendor page is also updated https://marketplace.atlassian.com/vendors/1214869/prism-project

**Comment by siavashs** [comment]
Done in #33
