### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by JanHegewald** [siavashs/Prism#43]
Based on #2, where several parameters were implemented, I would like to ask for the implementation of the 'theme' parameter. The dark theme is not always liked, and as Prism itself supports more than the dark theme, it would be great to have the ability to choose one of the other themes.

**Comment by siavashs** [comment]
Hi @JanHegewald unfortunately it's not possible to support a `theme` parameter for following reasons:
- PrismJS uses a global CSS for a page, we can't use multiple CSS resources for different `{code}` blocks
- Atlassian plugins can't dynamically change web resources, for example CSS in this case

Lastly in version 1.3.x Prism uses the default light theme.

**Comment by JanHegewald** [comment]
@siavashs : thanks for the reply! I understand your answer and also understand, that the default theme changed after 1.3.x

I'm therefore closing this issue, as I do not expect anything substantial to happen here.
