### ISSUE TITLE
Project sidebar not loading

### ISSUE THREAD

**Issue by bZhargal** [siavashs/Prism#48]
**Describe the bug**
The project sidebar is not displayed on the Agile Board page.
Pop-up menus Dashboards, Projects ...

**To Reproduce**
1. Go to 'Board's'
2. Click on 'Dashboards or Projects'
3. See error

**Screenshots**

![Screenshot from 2020-07-23 17-01-21](https://user-images.githubusercontent.com/44698249/88269788-3f60e000-cd07-11ea-9060-d43055e63d31.png)
![Screenshot from 2020-07-23 16-58-53](https://user-images.githubusercontent.com/44698249/88269796-41c33a00-cd07-11ea-81a6-c4e08022eff4.png)

**Expected behavior**
Brings up a menu with a choice of Dashboards or Projects

But on the Prism version [1.2.4] everything works as it should.

**Desktop**
  - Browser [all browser (Safari, Firefox, Chromium)]
  - JIRA Version [7.2.1]
  - Prism Version [1.3.1]

**Additional context**

**Comment by siavashs** [comment]
@bZhargal Thanks for the bug report, would you please check the browser console for any errors and share them?

**Comment by bZhargal** [comment]
@siavashs , Thanks for your reply.
Will the output from the browser console do this?

Uncaught TypeError: document.body is null
    handleJsException https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/b1952a15c3475283134f0572c086671e/_/download/contextbatch/js/gh-rapid-exception,-_super/batch.js?atlassian.aui.raphael.disabled=true:3
batch.js:3:1485
    handleJsException https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/b1952a15c3475283134f0572c086671e/_/download/contextbatch/js/gh-rapid-exception,-_super/batch.js?atlassian.aui.raphael.disabled=true:3


Uncaught TypeError: JIRA.ViewIssueTabs is undefined
    <anonymous> https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/9229d74053ba090b3f2cd363eda60124/_/download/contextbatch/js/greenhopper-rapid-non-gadget,atl.general,jira.general,gh-rapid,jira.global,jira.project.sidebar,com.atlassian.jira.projects.sidebar.init,-_super/batch.js?agile_global_admin_condition=true&atlassian.aui.raphael.disabled=true&healthcheck-resources=true&is-server-instance=true&is-system-admin=true&jag=true&jaguser=true&locale=en-UK&nps-acknowledged=true&nps-not-opted-out=true:10443
batch.js:10443:155

**Comment by patrickweegen** [comment]
The same problem occures when using JIRA Version 7.3.9 and the Prism version 1.3.1

**Comment by siavashs** [comment]
> @siavashs , Thanks for your reply.
> Will the output from the browser console do this?
> 
> ```js
> Uncaught TypeError: document.body is null
>     handleJsException https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/b1952a15c3475283134f0572c086671e/_/download/contextbatch/js/gh-rapid-exception,-_super/batch.js?atlassian.aui.raphael.disabled=true:3
> batch.js:3:1485
>     handleJsException https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/b1952a15c3475283134f0572c086671e/_/download/contextbatch/js/gh-rapid-exception,-_super/batch.js?atlassian.aui.raphael.disabled=true:3
> 
> 
> Uncaught TypeError: JIRA.ViewIssueTabs is undefined
>     <anonymous> https://xxx.xx/s/y-y/n4o5cj/72003/01ddec52bdca6bb7c332142ec09b934c/9229d74053ba090b3f2cd363eda60124/_/download/contextbatch/js/greenhopper-rapid-non-gadget,atl.general,jira.general,gh-rapid,jira.global,jira.project.sidebar,com.atlassian.jira.projects.sidebar.init,-_super/batch.js?agile_global_admin_condition=true&atlassian.aui.raphael.disabled=true&healthcheck-resources=true&is-server-instance=true&is-system-admin=true&jag=true&jaguser=true&locale=en-UK&nps-acknowledged=true&nps-not-opted-out=true:10443
> batch.js:10443:155
> ```

This seems to be related to new event handling code: https://github.com/siavashs/Prism/blob/master/src/main/resources/js/prism-init.js#L14
Although I can confirm the error happening on `Boards`, I did not manage to reproduce the bug so far.
As you can see in the screenshot, the sidebar and issues are loading just fine:
![image](https://user-images.githubusercontent.com/113189/89661867-889e5b80-d8d3-11ea-9360-1c1946d3f346.png)

**Comment by patrickweegen** [comment]
I think it has to be a board that contains issue of more than one project.

**Comment by siavashs** [comment]
> I think it has to be a board that contains issue of more than one project.

Still works:
![image](https://user-images.githubusercontent.com/113189/89663084-47a74680-d8d5-11ea-9f7e-005f1d41ad67.png)

**Comment by siavashs** [comment]
Would you also share the following information?
- Java version
- JIRA error/warning logs related to Prism plugin (if any)

**Comment by bZhargal** [comment]
> Would you also share the following information?
> 
>     * Java version
> 
>     * JIRA error/warning logs related to Prism plugin (if any)

Java version -  1.8.0_102.
Еhere are no more errors, except for the ones I dropped above

**Comment by siavashs** [comment]
This should be fix in 32f239f48b663600cd2ae7e56a28433b4b3789bf and will be released as part of [v1.3.3](https://github.com/siavashs/Prism/releases/tag/v1.3.3)

**Comment by bZhargal** [comment]
Thank you very much. After updating the plugin, everything works as it should.
