### ISSUE TITLE
jira 8.15/8.16 support

### ISSUE THREAD

**Issue by ihulsbus** [siavashs/Prism#54]
**Is your feature request related to a problem? Please describe.**
Blocked upgrade path to 8.15/8.16

**Describe the solution you'd like**
Support for 8.15/8.16

**Describe alternatives you've considered**
the alternative solution would be to disable or remove the plugin, which kind of defeats the point of this request

**Additional context**
We're in the process of preparing an upgrade to 8.15 but the Prism plugin is the only one blocking the upgrade at the moment. It would be nice of you could update the plugin to support Jira 8.15.0, 8.15.1 and 8.16.0 :)

**Comment by siavashs** [comment]
I just did a quick test on 8.16 and all seems fine.
I update the version compatibility on marketplace so you can use the plugin with JIRA 8.15/8.16 now.

**Comment by ihulsbus** [comment]
Confirmed working. Thanks for the quick action!
