### ISSUE TITLE
gherkin syntax doesn't work in Jira version 8.20.1

### ISSUE THREAD

**Issue by chauhanhitendra** [siavashs/Prism#61]
gherkin syntax doesn't work in Jira version 8.20.1

1. Go to any issue in Jira version 8.20.1
2. Edit description and following and save the issue.
{code:gherkin}

{code}

The description should be empty and no error, but there is an error. See screenshot.
![image](https://user-images.githubusercontent.com/85669390/153857710-b0b5c0e9-58a5-4bc4-9d7b-3f50034f5917.png)

**Comment by chauhanhitendra** [comment]
Can someone advise how to solve this issue ?

**Comment by siavashs** [comment]
This is duplicate of #57
